host: 0.0.0.0
port: 6370

# List of tasks
task:
  attributes:
    class: core.attributes.AttrbutesHandler
    models: 
      - GoogleVertex_Vision_PPE: infra.api.google_detect.detect_ppe
      - Joseph: infra.api.internalmodels.face_attr.predict
      - LUUP_helmet_detection: infra.api.internalmodels.luup_helmet.predict
      - LUUP_sidewalk_detection1025: infra.api.internalmodels.luup_sidewalk.predict
  face_detection:
    class: core.detection.FaceDetectionHandler
    models: 
       - GoogleCloudVision: infra.api.google_detect.detect_faces
       - Joseph: infra.api.internalmodels.face_detect.predict
       - LuupVehicles: infra.api.internalmodels.luup_vehicles.predict
       
logging:
  version: 1
  objects:
    queue:
      class: queue.Queue
      maxsize: -1
  formatters:
    simple:
      format: '{"level":"%(levelname)s","time":"%(asctime)s","caller":"%(pathname)s:%(lineno)d","message":"%(message)s"}'
      datefmt: '%Y-%m-%dT%H:%M:%S%Z'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG  # need to change level when for production
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      filename: 'server.log'
      formatter: simple
    queue_listener:
      class: josephlogging.listener.QueueListenerHandler
      queue: cfg://objects.queue
      handlers:
        - cfg://handlers.file
  root:
    level: INFO  # need to change level when for production
    handlers:
      - console
